// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Temporada2025.Backend;

#nullable disable

namespace Temporada2025.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250806193944_primeraMigracion")]
    partial class primeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Temporada2025.Backend.Models.Estadistica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Asistencias")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaJornada")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Goles")
                        .HasColumnType("int");

                    b.Property<Guid>("JugadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PartidosJugados")
                        .HasColumnType("int");

                    b.Property<double>("Puntaje")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.ToTable("TblEstadistica");
                });

            modelBuilder.Entity("Temporada2025.Backend.Models.Jugador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dorsal")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posición")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblJugador");
                });

            modelBuilder.Entity("Temporada2025.Backend.Models.Estadistica", b =>
                {
                    b.HasOne("Temporada2025.Backend.Models.Jugador", "Jugador")
                        .WithMany("Estadisticas")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("Temporada2025.Backend.Models.Jugador", b =>
                {
                    b.Navigation("Estadisticas");
                });
#pragma warning restore 612, 618
        }
    }
}
